# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2cf9fa6d40b17f42b4da68ae4eb03c736bda5c9d00f0f143a2cf77ef976c637ef703afc644bf94c4c2250383155169fb663fac27a32e4259e3ba5f94e72b9d36

test:
  secret_key_base: 781b0b924a59a8e4dbc03bbb01a7b891782f310e34075931024697502d651fdb45ecab3e887f3c0bdea37637da3b24ed04344882c3faa51ce2ac255b8a3c371b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
